apiVersion: v1
kind: Service
metadata:
  name: simple-uor
  labels:
    app.kubernetes.io/name: simple-uor
    app.kubernetes.io/instance: simple-uor
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: simple-uor
    app.kubernetes.io/instance: simple-uor
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
